name: check

on:
  pull_request: []

jobs:
  gotest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.18']
    name: go v${{ matrix.go }} test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go test -v
  golangci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        golangci: ['1.45.2']
        go: ['1.18']
    name: golangci-lint v${{ matrix.golangci }}, go v${{ matrix.go }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v${{ matrix.golangci }}
          skip-go-installation: true
